---
- name: "nexus"
  box:
    vb: "geerlingguy/centos7"
  nics:
    - type: "private_network"
      ip_addr: "192.168.99.50"
  ram: "4096"
  vcpu: "1"
- name: "slave-01"
  box:
    vb: "geerlingguy/centos7"
  nics:
    - type: "private_network"
      ip_addr: "192.168.99.51"
  ram: "2048"
  vcpu: "1"
- name: "slave-02"
  box:
    vb: "geerlingguy/centos7"
  nics:
    - type: "private_network"
      ip_addr: "192.168.99.52"
  ram: "2048"
  vcpu: "1"
- name: "jenkins"
  box:
    vb: "geerlingguy/centos7"
  nics:
    - type: "private_network"
      ip_addr: "192.168.99.53"
  ports:
    - guest_port: "8080"
  ram: "2048"
  vcpu: "1"
